# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-CcHaMDX-C8sztk0ICNBdCidDEp54x6V
"""

!pip install streamlit
!pip install mediapipe

import streamlit as st
import numpy as np
import mediapipe as mp
import cv2
from scipy.spatial import distance as dist
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

st.set_page_config(page_title="Driver Drowsiness Detector",page_icon="🚗",layout="centered")
st.title("🚗 Driver Drowsiness & Yawn Detector")
st.write("Take a snapshot or upload an image to check fatigue state in real time.")

!wget -q -O face_landmarker.task https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task

BaseOptions=mp.tasks.BaseOptions
FaceLandmarker=vision.FaceLandmarker
FaceLandmarkerOptions=vision.FaceLandmarkerOptions
VisionRunningMode=vision.RunningMode

left_eye_idx=[33,160,158,133,153,144]
right_eye_idx=[362,385,387,263,373,380]
mouth_indices=[13, 14, 78, 308]

def calculate_ear(landmark,eye_indices,img_w,img_h):
  pts=[]
  for idx in eye_indices:
    lm=landmark[idx]
    pts.append((lm.x*img_w,lm.y*img_h))
  A=dist.euclidean(pts[1],pts[5])
  B=dist.euclidean(pts[2],pts[4])
  C=dist.euclidean(pts[0],pts[3])
  ear=(A+B)/(2*C)
  return ear


def calculate_mar(landmarks,mouth_indices,img_w,img_h):
  pts=[]
  for idx in mouth_indices:
    lm=landmarks[idx]
    pts.append((lm.x*img_w,lm.y*img_h))
  vertical_dist=dist.euclidean(pts[0],pts[1])
  horizontal_dist=dist.euclidean(pts[2],pts[3])
  mar=vertical_dist/horizontal_dist
  return mar

@st.cache_resource
def load_detector():
  base_options=python.BaseOptions(model_asset_path='face_landmarker.task')
  options=vision.FaceLandmarkerOptions(
      base_options=base_options,
      output_face_blendshapes=False,
      output_facial_transformation_matrixes=False,
      num_faces=1
  )
  return vision.FaceLandmarker.create_from_options(options)
detector=load_detector()

st.sidebar.header("Threshold Settings")
ear_thres=st.sidebar.slider("EAR Threshold (Eye Closure)", 0.10,0.35,0.20,0.01)
mar_thres=st.sidebar.slider("MAR Threshold (Yawn)", 0.30,0.80, 0.50,0.05)

img_file=st.camera_input("Take a picture from your camera")

if img_file is not None:
  file_bytes=np.asarray(bytearray(img_file.read()),dtype=np.uint8)
  image=cv2.imdecode(file_bytes,1)
  h, w, _=image.shape
  rgb_img=cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
  mp_image=mp.Image(image_format=mp.ImageFormat.SRGB,data=rgb_img)
  detection_result=detector.detect(mp_image)
  if detection_result.face_landmarks:
    landmarks=detection_result.face_landmarks[0]
    left_ear=calculate_ear(landmarks,left_eye_idx,w,h)
    right_ear=calculate_ear(landmarks,right_eye_idx,w,h)
    avg_ear=(left_ear+right_ear)/2.0
    mar=calculate_mar(landmarks,mouth_indices,w,h)
    col1, col2 = st.columns(2)
    col1.metric("Eye Aspect Ratio (EAR)", f"{avg_ear:.3f}")
    col2.metric("Mouth Aspect Ratio (MAR)", f"{mar:.3f}")

    ear_thres=0.20
    mar_thres=0.50

    if avg_ear<ear_thres and mar>mar_thres:
      st.error("Sleeping and Yawning detected 😴")
    elif avg_ear < ear_thres:
        st.error("DROWSINESS DETECTED! EYES CLOSED!")
    elif mar > mar_thres:
        st.error("Status: Yawning Detected 🥱")
    else:
        st.success("Status: Fully Awake 😎")
  else:
    st.warning("No face detected! Try again")





